### ISSUE TITLE
migration文件中字段或备注有问号时vsprintf()报错

### ISSUE THREAD

**Issue by HeJiaNong** [overtrue/laravel-query-logger#12]
在migration文件中name字段包含问号❓
![image](https://user-images.githubusercontent.com/39476157/59002377-c671a100-8844-11e9-8cb6-e9b70e613bba.png)

在sql语句中看到name字段中的问号被替换成了%s,导致vsprintf()报错?
![image](https://user-images.githubusercontent.com/39476157/59002396-d12c3600-8844-11e9-9ea5-90ac4c17931f.png)

试了下直接在sql语句中加%s发现又没问题的呀...
![image](https://user-images.githubusercontent.com/39476157/59002756-14d36f80-8846-11e9-8cbc-0eed5ae70115.png)
![image](https://user-images.githubusercontent.com/39476157/59002767-1c931400-8846-11e9-8964-77b85a226834.png)

**Comment by overtrue** [comment]
字段名包含问号？？？？？？？？？，这是谁发明的奇葩设计？

HeJiaNong <notifications@github.com>于2019年6月6日 周四上午10:32写道：

**Comment by HeJiaNong** [comment]
哈哈，也是无意间在备注里面写了问号，只有避免写问号了
