### ISSUE TITLE
更新今晚的版本之后，一直报错Undefined variable: duration

### ISSUE THREAD

**Issue by gdmec07150942** [overtrue/laravel-query-logger#19]
在overtrue/laravel-query-logger/src/ServiceProvider.php:41,缺失定义了$duration 变量
![image](https://user-images.githubusercontent.com/22065379/75897913-47ada100-5e74-11ea-8675-712825d3f781.png)

**Comment by overtrue** [comment]
抱歉，已经发了新版

gdmec07150942 <notifications@github.com>于2020年3月5日 周四上午12:00写道：
