### ISSUE TITLE
这里建议修改一下

### ISSUE THREAD

**Issue by jjsty1e** [overtrue/laravel-query-logger#32]
https://github.com/overtrue/laravel-query-logger/blob/ad76e00bd08a9d1ec3e6679dd820724348f44c28/src/ServiceProvider.php#L36

建议修改为：
```php
$this->app['events']->listen('illuminate.query', function (QueryExecuted $query) { 
```

因为`DB::listen`会创建一个连接，实际上有些情况下是不需要连接db的。

**Comment by overtrue** [comment]
感谢，已更新
