### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by iwindy** [overtrue/laravel-query-logger#33]
https://github.com/overtrue/laravel-query-logger/blob/d9299f4f6523eb4a1c84412d75a757026189f9b5/src/ServiceProvider.php#L36
这句的写法在laravel8以下版本不兼容
建议修改成，$this->app['events']->listen(QueryExecuted::class, function (QueryExecuted $query) {

**Comment by overtrue** [comment]
提个PR？

发自我的iPhone
