### ISSUE TITLE
关闭 Auto-Discovery？

### ISSUE THREAD

**Issue by mingyoung** [overtrue/laravel-query-logger#4]
https://github.com/overtrue/laravel-query-logger/blob/3d9f54faa5ac5fd757098a93e386dc7e6ae9358a/composer.json#L20-L24

production 导致日志剧增，这个手动注册会不会好点？

**Comment by mingyoung** [comment]
![image](https://user-images.githubusercontent.com/6228858/46243094-b0ccf180-c402-11e8-816a-fc856115420e.png)
当我没说🤣

**Comment by mouyong** [comment]
在 composer.json 关闭自动注册本包，然后在 AppServiceProvider 判断环境手动注册可以变相解决该问题。

**Comment by overtrue** [comment]
其实可以考虑移除自动发现

张铭阳 <notifications@github.com>于2018年9月29日 周六下午4:14写道：

**Comment by bolechen** [comment]
本地开发 phpunit 的时候也会写日志，是否考虑加个环境变量的选择，类似 
```DEBUGBAR_ENABLED=true```

**Comment by overtrue** [comment]
@bolechen 搞定，麻烦体验。

**Comment by bolechen** [comment]
效率！

安正超 <notifications@github.com>于2019年3月12日 周二17:14写道：
